apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
    TENBIS_USER_TOKEN: {{ .Values.secrets.tenbisUser | b64enc }}
    SLACK_WEBHOOK: {{ .Values.secrets.slackWebhook | b64enc }}
    SLACK_SIGNING_SECRET: {{ .Values.secrets.SlackSigningSecret | b64enc }}
    SLACK_BOT_TOKEN: {{ .Values.secrets.SlackBotToken | b64enc }}
    SLACK_APP_TOKEN: {{ .Values.secrets.SlackAppToken | b64enc }}
    SLACK_NOTIFICATION_CHANNEL: {{ .Values.secrets.SlackNotificationChannel | b64enc }}
    DB_FILE_PATH: {{ .Values.config.dbPath | b64enc }}
